version: '2'

services:
  rabbitmq:
    image: 'rabbitmq:3.7-management'
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
volumes:
  rabbitmq_data:
    driver: local
